package com.iare.placementportal.ai;

public enum AiIntentType {
    COMPANY_INFO,
    SELECTED_STUDENTS_BY_COMPANY,
    SELECTED_COUNT_BY_COMPANY,
    COMPANY_VISIT_COUNT_BY_YEAR,
    COMPANIES_VISITED_BY_YEAR,
    HIGHEST_PACKAGE_BY_YEAR,
    AVERAGE_PACKAGE_BY_YEAR,
    DRIVE_DETAILS_BY_COMPANY,
    PLACEMENT_STATISTICS_BY_COMPANY,
    ACTIVE_NOTICES,
    RESOURCES_BY_COMPANY,
    GENERAL_CHAT,
    UNKNOWN
}
