spring.application.name=placementportal

server.port=${PORT:8080}

# ==========================
# PostgreSQL (Supabase)
# ==========================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / Hibernate
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

===<<<<<<< HEAD
=======
# ==========================
# File Upload
# ==========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# Hikari connection pool tweaks for cloud (Render)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.b8b70f80e0a17fef22dea35b
====
# Cloudinary
# ==========================

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}



# =========================
# OLLAMA AI CONFIG
# =========================


ai.ollama.base-url=${AI_OLLAMA_BASE_URL:https://pessimism-slacking-virtuous.ngrok-free.dev}
ai.ollama.model=${AI_OLLAMA_MODEL:llama3.2:1b}
