spring.application.name=placementportal
server.port=${PORT:8080}

# ==========================
# PostgreSQL / Supabase
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ==========================
# File Upload
# ==========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# ==========================
# Hikari Pool - Render/Supabase Stable
# ==========================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# ==========================
# Cloudinary
# ==========================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ==========================
# AI / Ollama
# ==========================

ai.ollama.base-url=${AI_OLLAMA_BASE_URL:https://pessimism-slacking-virtuous.ngrok-free.dev}
ai.ollama.model=${AI_OLLAMA_MODEL:llama3.2:1b}
